language: java

install:
  - mvn install -U -DskipTests=true

before_script:
  - mysql -uroot -e 'SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED'
  - mysql -e 'show variables;'
  - cat test-schema.sql | mysql -uroot

script:
  - mvn clean test

branches:
  only:
    - master
