language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

before_script:
  - mysql -uroot -e 'SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED'
  - mysql -e 'show variables;'
  - cat test-schema.sql | mysql -uroot

addons:
  sonarqube:
    organization: "cpollet-github"
    token:
      secure: $SONARQUBE_TOKEN

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

branches:
  only:
    - master
